# Generated by Django 5.0.6 on 2024-07-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_store_custo_last_na_2e448d_idx'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
                VALUES ('collection1')
        """,
        """
            DELETE FROM store_collection 
                WHERE title = 'collection1';
        """
                          )
    ]
