# Generated by Django 5.0.6 on 2024-07-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20240707_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place_at',
            new_name='placed_at',
        ),
    ]
