# Generated by Django 5.0.6 on 2024-07-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_rename_exerciselog_exerciselogmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselogmeta',
            name='log_id',
            field=models.PositiveSmallIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
