# Generated by Django 5.0.6 on 2024-07-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_alter_exerciselogmeta_log_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselogmeta',
            name='log_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
