# Generated by Django 5.0.6 on 2024-07-13 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_alter_exerciselogmeta_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fitness.exercisetype')),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exerciselogmeta')),
            ],
        ),
    ]
