# Generated by Django 5.0.6 on 2024-07-13 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_exerciselog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseLogMeta',
            new_name='ExerciseRoutine',
        ),
        migrations.AlterModelOptions(
            name='exerciseroutine',
            options={'verbose_name': 'Exercise Detail', 'verbose_name_plural': 'Exercise Details'},
        ),
        migrations.AlterModelOptions(
            name='exercisetype',
            options={'verbose_name': 'Exercise Type', 'verbose_name_plural': 'Exercise Types'},
        ),
    ]
