# Generated by Django 5.0.6 on 2024-07-13 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_rename_exerciselogmeta_exerciseroutine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('equip_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('units_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='exerciseroutine',
            options={'verbose_name': 'Exercise Routine', 'verbose_name_plural': 'Exercise Routines'},
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='equip_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='fitness.equipmenttype'),
            preserve_default=False,
        ),
    ]
